packages:
  - products/*
  - docs
  - setup

catalog:
  '@vitest/coverage-v8': ^4.0.5
  '@vitest/ui': ^4.0.5
  prettier: 3.6.2
  typescript: 5.9.3
  vitest: ^4.0.5
  zod: ^4.1.12

catalogs:
  backend:
    '@cloudflare/workers-types': ^4.20251014.0
    '@hono/zod-openapi': ^1.1.4
    '@scalar/hono-api-reference': ^0.9.22
    '@types/pg': ^8.15.6
    drizzle-kit: ^0.31.6
    drizzle-orm: ^0.44.7
    hono: ^4.10.4
    pg: ^8.16.3
    wrangler: ^4.45.3
    zod-openapi-share: ^0.0.11
  docs:
    '@astrojs/check': ^0.9.5
    astro: ^5.15.3
    prettier-plugin-astro: ^0.14.1
  frontend:
    '@eslint/js': ^9.38.0
    '@hookform/error-message': ^2.0.1
    '@hookform/resolvers': ^5.2.2
    '@sentry/react': ^10.22.0
    '@sentry/vite-plugin': ^4.6.0
    '@tanstack/react-query': ^5.90.5
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    '@vitejs/plugin-react-swc': ^4.2.0
    eslint: ^9.38.0
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.24
    globals: ^16.4.0
    happy-dom: ^20.0.10
    openapi-fetch: ^0.15.0
    openapi-react-query: ^0.5.1
    openapi-typescript: ^7.10.1
    react: ^19.2.0
    react-dom: ^19.2.0
    react-hook-form: ^7.65.0
    react-router: ^7.9.5
    typescript-eslint: ^8.46.2
    vite: ^7.1.12
  notify:
    '@cloudflare/vitest-pool-workers': ^0.8.71
  node:
    tsx: ^4.20.6
  root:
    turbo: ^2.5.8
  setup:
    dotenv: ^17.2.3
    dotenv-caster: ^2.1.23

ignoredBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
