graph LR;
    db[("Database (Xata Lite)")]
    hyperdrive(("Hyperdrive"))
    drizzle["Drizzle (ORM)"]
    hono["Hono (Web API)"]
    frontend["Vite + React"]
    idp{{"Identity Provider (Google, GitHub, etc.)"}}
    user["User"]

    db <--> hyperdrive
    hyperdrive <--> drizzle
    subgraph "Backend (Cloudflare Workers)"
        drizzle
        drizzle <--> hono
    end
    hono <--with session--> frontend
    subgraph "Frontend (Cloudflare Workers)"
        frontend
    end
    idp <-.authentication.-> user
    idp --.add authentication info.--> hono
    frontend -.redirect.-> idp
    user <--with session--> frontend
    user -.without session.-> frontend
